require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/l_ine_items", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # LIneItem. As you add validations to LIneItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      LIneItem.create! valid_attributes
      get l_ine_items_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      l_ine_item = LIneItem.create! valid_attributes
      get l_ine_item_url(l_ine_item)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_l_ine_item_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      l_ine_item = LIneItem.create! valid_attributes
      get edit_l_ine_item_url(l_ine_item)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new LIneItem" do
        expect {
          post l_ine_items_url, params: { l_ine_item: valid_attributes }
        }.to change(LIneItem, :count).by(1)
      end

      it "redirects to the created l_ine_item" do
        post l_ine_items_url, params: { l_ine_item: valid_attributes }
        expect(response).to redirect_to(l_ine_item_url(LIneItem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new LIneItem" do
        expect {
          post l_ine_items_url, params: { l_ine_item: invalid_attributes }
        }.to change(LIneItem, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post l_ine_items_url, params: { l_ine_item: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested l_ine_item" do
        l_ine_item = LIneItem.create! valid_attributes
        patch l_ine_item_url(l_ine_item), params: { l_ine_item: new_attributes }
        l_ine_item.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the l_ine_item" do
        l_ine_item = LIneItem.create! valid_attributes
        patch l_ine_item_url(l_ine_item), params: { l_ine_item: new_attributes }
        l_ine_item.reload
        expect(response).to redirect_to(l_ine_item_url(l_ine_item))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        l_ine_item = LIneItem.create! valid_attributes
        patch l_ine_item_url(l_ine_item), params: { l_ine_item: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested l_ine_item" do
      l_ine_item = LIneItem.create! valid_attributes
      expect {
        delete l_ine_item_url(l_ine_item)
      }.to change(LIneItem, :count).by(-1)
    end

    it "redirects to the l_ine_items list" do
      l_ine_item = LIneItem.create! valid_attributes
      delete l_ine_item_url(l_ine_item)
      expect(response).to redirect_to(l_ine_items_url)
    end
  end
end
